server:
  port: 8088
  use-forward-headers: true
  tomcat:
    remote-ip-header: X-Real-IP
    protocol-header: X-Forward-Proto
    max-threads: 32
    min-spare-threads: 2
  servlet:
    session:
      cookie:
        name: PMST

spring:
  application:
    name: picman2
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/picman?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8  # change host and database
    username: root  # change username
    password: 123456  # change password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 30MB
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379

security:
  oauth2:
    client:
      client-id: picman2
      client-secret: abcdef123456
      access-token-uri: http://localhost:7011/oauth/token  # change sac private address
      user-authorization-uri: http://10.11.7.3:7011/oauth/authorize  # change sac public address
    resource:
      user-info-uri: http://localhost:7011/api/userinfo  # change sac private address

picman:
  storage:
    base-path: ./testdata
  jwt:
    sign-key: changeme  # for test, no effects
  swagger:
    enable: true  # change
  rgw-access-key: 123456  # change
